name: Ejemplo simple de Github Actions

on:
    push:
        branches:
        - master


jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: mostrar mensaje
        run: echo "hola mundo github actions"

    